global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'wayang-models'
    metrics_path: '/metrics'
    static_configs:
      - targets: ['wayang-models:8080']
        labels:
          application: 'wayang-models'
  
  - job_name: 'otel-collector'
    static_configs:
      - targets: ['otel-collector:8888']